name: Chatmeter Poller

on:
  schedule:
    - cron: "*/30 * * * *" # every 30 minutes
  workflow_dispatch:

jobs:
  poll:
    runs-on: ubuntu-latest
    steps:
      - name: Call poll-v2
        run: |
          curl -sS -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            "${{ secrets.BASE_URL }}/api/poll-v2?minutes=60&max=20" | jq .
