name: Poll Chatmeter (every 15 min)

on:
  schedule:
    - cron: "*/15 * * * *"   # every 15 minutes (UTC)
  workflow_dispatch: {}       # allow manual run

jobs:
  poll:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel poller
        env:
          BASE_URL: https://drivo-chatmeter-bridge.vercel.app
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
          ACCOUNT_ID: 6646597de7a19144ba286d92
        run: |
          set -e
          curl -sS -H "Authorization: Bearer $CRON_SECRET" \
            "$BASE_URL/api/poll-v2?minutes=20&accountId=$ACCOUNT_ID&max=50"


