name: Chatmeter Bridge Poller

on:
  schedule:
    - cron: "*/15 * * * *"   # every 15 minutes (UTC)
  workflow_dispatch: {}       # allow manual run

concurrency:
  group: chatmeter-poller
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:
      - name: Hit poll-v2 (collect new reviews)
        run: |
          curl -fsS -H "Authorization: Bearer $CRON_SECRET" \
            "$BASE_URL/api/poll-v2?minutes=30&max=50"
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          CRON_SECRET: ${{ secrets.CRON_SECRET }}

      - name: Fix missing (pulls detail text when available)
        run: |
          curl -fsS -H "Authorization: Bearer $CRON_SECRET" \
            "$BASE_URL/api/fix-missing?minutes=30&limit=200"
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          CRON_SECRET: ${{ secrets.CRON_SECRET }}

      - name: Backfill links (Yelp/Google/Trustpilot link note if no text)
        run: |
          curl -fsS -H "Authorization: Bearer $CRON_SECRET" \
            "$BASE_URL/api/fix-missing-links?minutes=30&limit=200"
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
